# SPECIAL CHARACTERS
BASE_CHARACTERS = {'*', ',', '-'}

MIN_CHARACTERS = {*BASE_CHARACTERS}
HOUR_CHARACTERS = {*BASE_CHARACTERS}
DAY_CHARACTERS = {*BASE_CHARACTERS}
MONTH_CHARACTERS = {*BASE_CHARACTERS}
WEEK_CHARACTERS = {*BASE_CHARACTERS}

# ALLOWED VALUES
MIN_VALUES = [(0, 59)]
HOUR_VALUES = [(0, 23)]
DAY_VALUES = [(1, 31)]
MONTH_VALUES = [(1, 12)]
WEEK_VALUES = [(0, 6)]